//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakturisanje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class DokumentFakture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DokumentFakture()
        {
            this.StavkaFaktures = new HashSet<StavkaFakture>();
        }

        [DisplayName("Datum fakture")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DatumFakture { get; set; }

        [DisplayName("Broj fakture")]
        public string RedniBroj { get; set; }

        [DisplayName("Ukupno")]
        public int Ukupno { get; set; }
    
        public virtual ICollection<StavkaFakture> StavkaFaktures { get; set; }
    }
}
