//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakturisanje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaFakture
    {
        public int RedniBroj { get; set; }
        public int Kolicina { get; set; }
        public double Cena { get; set; }
        public double Ukupno { get; set; }
        public string FK_DokumentFakture { get; set; }
    
        public virtual DokumentFakture DokumentFakture { get; set; }
    }
}
